config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  get "about" => 'welcome#about'

  root 'welcome#index'

  resources :articles do 
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  		@articles = Article.all
  end

  def new
  		@article = Article.new
  end

  def create
  		Article.create(params.require(:article).permit(:title, :description))

  		redirect_to articles_path
  end

  def edit 
  		@article = Article.find(params[:id])
  end

  def update
		@article = Article.find(params[:id])
		permitted_columns = params.require(:article).permit(:title, :description)
		@article.update_attributes(permitted_columns)

		redirect_to articles_path
	end

	def show
		@article = Article.find(params[:id])

	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path, notice: "Delete Success"
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def create
		@article = Article.find(params[:article_id])
		permitted_columns = params[:comment].permit(:commenter, :description)
		@comment = @article.comments.create(permitted_columns)

		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy

		redirect_to article_path(@article)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def bootstrap_class_for(flash_type)
	case flash_type
		when :success
			"alert-success"
		when :error
			"alert-error"
		when :alert
			"alert-block"
		when :notice
			"alert-info"
		else
			flash_type.to_s
	end
end




end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	
<% end %>

app/views/articles/edit.html.erb
<h1> Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1> Articles</h1>
<table class="table table-striped">
	<thread>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Description</th>
			<th>Actions</th>
		</tr>
	</thread>
	<tbody>
		<% @articles.each do |article| %>
			<tr>
				<td><%= article.id %></td>
				<td><%= link_to article.title, article %></td>
				<td><%= article.description %> </td>
				<td>

					<%= link_to 'Edit', edit_article_path(article), :class => 'btn btn-mini' %>
					
					<%= link_to 'Delete', article_path(article), :method => :delete, :data => {confirm: 'Are you sure?'}, :class => 'btn btn-mini btn-danger'  %>

				</td>
			<tr>
	</tbody>


<% end %>

<%= link_to 'New Article', new_article_path, :class => 'btn btn-primary' %>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<p>
	<%= @article.title %><br>
</p>

<p>
	<%= @article.description %><br>
</p>

<h2>Comments</h2>
	<% @article.comments.each do |comment| %>
		<p>
			<strong>Commenter:</strong>
			<%= comment.commenter %>
		</p>

		<p>
			<strong>Comment:</strong>
			<%= comment.description %>
		</p>

		<%= link_to 'Delete Comment',
												[@article, comment],
												method: :delete,
												data: { confirm: 'Are you sure?' } %>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
		<p>
			<%= f.label :commenter %><br />
			<%= f.text_field :commenter %>
		</p>

		<p>
			<%= f.label :description %><br />
			<%= f.text_area :description %>
		</p>

		<p>
			<%= f.submit %>
		</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" <%= link_to "Home", root_path %></li> </a>

	</div>
<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><%= link_to "My articles", articles_path %></li>
			<li><%= link_to "About Us", about_path %></li>

		</ul>
	</div><!-- /.navbar-collapse -->
</nav>

	<% flash.each do |name, msg| -%>
		<%= content_tag :div, msg, class: name %>
	<% end -%>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/welcome/about.html.erb
<!DOCTYPE html>
<html>
	<body>

		<h1> About </h1>

		<p> This app is a prototype built by John Mullin for ORM Technologies. It's purpose serves to deonstrate John's:</p>

		<ul>
  		<li type="square">Capabilities in learning a new language and new concepts</li>
 		 <li type="square">Pre-established foundation in Ruby</li>
  		<li type="square">Passion for optimization over web-based applications</li>
		</ul>

		<h3> Contact </h3>

		<p> Email:  jmullin@smu.edu</p>
		<p> Phone:  602.999.0056</p>
		<p> Address: 6638 Airline Rd. Dallas, TX 75205</p

	</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
	<body>

		<h1> Welcome! </h1>


		<p> Here you will find a curation of the most interesting articles and videos about Modern Medical Advancement using rapidly evolving technologies. </p>

		<object width="425" height="344"><param name="movie" value="http://swf.tubechop.com/tubechop.swf?vurl=sXz0boNmwak&start=2010&end=2148&cid=6506723"></param><embed src="http://swf.tubechop.com/tubechop.swf?vurl=sXz0boNmwak&start=2010&end=2148&cid=6506723" type="application/x-shockwave-flash" allowfullscreen="true" width="425" height="344"></embed></object>

		<p> This app is a prototype built by John Mullin for ORM Technologies. It's purpose serves to deonstrate John's:</p>

		<ul>
  		<li type="square">Capabilities in learning a new language and new concepts</li>
 		 <li type="square">Pre-established foundation in Ruby</li>
  		<li type="square">Passion for optimization over web-based applications</li>
		</ul>

		<%= link_to 'My Blog', articles_url %>

		<h3> Contact </h3>

		<p> Email:  jmullin@smu.edu</p>
		<p> Phone:  602.999.0056</p>
		<p> Address: 6638 Airline Rd. Dallas, TX 75205</p

	</body>
</html>